apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.global.deploy.name }}-tls
spec:
  commonName: {{ .Values.global.service.name }}
  dnsNames:
  - {{ .Values.global.service.name }}
  - {{ .Values.global.service.name }}.cp4s
  - {{ .Values.global.service.name }}.cp4s.svc
  - {{ .Values.global.service.name }}.cp4s.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: cp4s-issuer
  secretName: {{ .Values.global.deploy.name }}-tls
