apiVersion: v1
data:
  ci_id: {{ .Values.global.bridge.ci_id | b64enc }}
  ci_secret: {{ .Values.global.bridge.ci_secret | b64enc }}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.global.bridge.name }}
type: Opaque
