apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.service.name }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.global.deploy.name }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.global.service.port }}
      targetPort: {{ .Values.global.service.targetPort }}
      name: iam-bridge-service
  type: ClusterIP
